---
# This is a role for setting up the client.
- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Install packages
  apt:
    pkg:
     - nmap
     - git
     - python3.8
     - python3-pip
     - apache2
     - net-tools
     - python2-minimal
    update_cache: yes

# lab 14


- name: Install twisted python-module
  shell: pip3 install twisted

- name: Install sslstrip
  git:
    repo: https://github.com/moxie0/sslstrip.git
    dest: /home/user/sslstrip/

- name: Run sslstrip
  shell: python2 setup.py install
  args:
    chdir: /home/user/sslstrip/

...
