---
# This is a role for setting up the client.
- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Install packages
  apt:
    pkg:
     - nmap
     - git
     - python3.8
     - python3-pip
     - apache2
     - net-tools
     - python2-minimal
     - curl
     - wget
    update_cache: yes

# lab 14

- name: Copy setup.sh to the remote machine
  copy:
    src: setup.sh
    dest: /tmp/setup.sh
    mode: 0755

- name: Run setup.sh
  shell: /tmp/setup.sh
  become: true

...
