---
# This is a role for setting up the client.
- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.40.5 server'

- name: Install packages
  apt:
    pkg:
     - nmap
     - git
     - python3.8
     - python3-pip
     - apache2
     - net-tools
    update_cache: yes

- name: Change user to client
  expect:
   command: "su client"
   responses:
    Password: "password"

- name: Clone 'social-engineer-toolkit'
  git:
    repo: 'https://github.com/trustedsec/social-engineer-toolkit.git'
    dest: /home/client/setoolkit/

- name: Install requirements
  shell: pip3 install -r requirements.txt
  args:
    chdir: /home/client/setoolkit/
    
- name: Run setup.py
  shell: python3 setup.py
  args:
    chdir: /home/client/setoolkit/

- name: Create directory for Metasploit
  file:
    path: "/home/client/msf"
    state: directory
    mode: "0755"

- name: Download metasploit
  get_url:
    url: https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb
    dest: /home/client/msf/msfinstall
    mode: '0755'

- name: Run msfinstall script
  shell: "./msfinstall"
  args:
    chdir: /home/client/msf

...
