---
# This is a role for setting up the client.
- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Install packages
  apt:
    pkg:
     - nmap
     - git
     - python3.8
     - python3-pip
     - apache2
     - net-tools
     - sqlmap
    update_cache: yes

# LAB 13
- name: Clone SQLmap repository
  git:
    repo: https://github.com/sqlmapproject/sqlmap.git
    dest: /home/client/sqlmap-dev
    depth: 1

...
