---
# This is a role for setting up the client.
- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Install packages
  apt:
    pkg:
     - nmap
     - git
     - python3.8
     - python3-pip
     - apache2
     - net-tools
     - build-essential
     - nano
     - traceroute
     - iputils-ping
    update_cache: yes

- name: Copy buffer1
  copy:
    src: buffer1
    dest: /home/client/buffer1
    owner: user
    mode: '0711'

- name: Copy buffer2
  copy:
    src: buffer2
    dest: /home/client/buffer2
    owner: user
    mode: '0711'

...
