---
# This is a role for setting up the client.
- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Install packages
  apt:
    pkg:
     - nmap
     - git
     - python3.8
     - python3-pip
     - apache2
     - net-tools
     - python2-minimal
    update_cache: yes

# lab 14
# - name: Install Conda
#   block:
#     - name: Download anaconda
#       get_url:
#         url: https://repo.anaconda.com/archive/Anaconda3-2023.07-1-Linux-x86_64.sh
#         dest: /tmp/install-anaconda.sh
#         mode: 0550
#     - name: Create conda folder
#       become: True
#       file:
#         path: /opt/anaconda3
#         state: directory
#         owner: client
#         mode: 755
#         recurse: yes
#     - name: Run the installer
#       shell: /tmp/install-anaconda.sh -b -u -p /opt/anaconda3
#     - name: Remove the installer
#       file:
#         state: absent
#         path: /tmp/install-anaconda.sh
#     - name: Add anaconda bin to path
#       become: True
#       shell: echo 'export PATH=/opt/anaconda3/bin:$PATH' >> /etc/profile
#     - name: conda - read permission for all
#       become: True
#       file:
#         path: /opt/anaconda3
#         mode: +r
#         recurse: yes
#     - name: conda - execution permission for all
#       become: True
#       file:
#         path: /opt/anaconda3/bin
#         mode: +x
#         recurse: yes

- name: Install Conda
  block:
    - name: Download Miniconda
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-py38_23.5.2-0-Linux-x86_64.sh
        dest: /tmp/install-miniconda.sh
        checksum: sha256:e2a4438671e0e42c5bba14cb51de6ce9763938184d6ca2967340bbe972bbe7e6
        mode: 0550
    - name: Create conda folder
      become: True
      file:
        path: /opt/miniconda3
        state: directory
        owner: ubuntu
        mode: 755
        recurse: yes
    - name: Run the installer
      shell: /tmp/install-miniconda.sh -b -u -p /opt/miniconda3
    - name: Remove the installer
      file:
        state: absent
        path: /tmp/install-miniconda.sh
    - name: Add miniconda bin to path
      become: True
      shell: echo 'export PATH=/opt/miniconda3/bin:$PATH' >> /etc/profile
    - name: conda - read permission for all
      become: True
      file:
        path: /opt/miniconda3
        mode: +r
        recurse: yes
    - name: conda - execution permission for all
      become: True
      file:
        path: /opt/miniconda3/bin
        mode: +x
        recurse: yes

- name: Install sslstrip
  git:
    repo: https://github.com/moxie0/sslstrip.git
    dest: /home/user/sslstrip/

- name: activate conda
  shell: /opt/miniconda3/bin/activate
  args:
    chdir: /home/user/sslstrip/

- name: create sslstrip env
  shell: conda create -n sslstrip python=2.7 service_identity pyOpenSSL Twisted
  args:
    chdir: /home/user/sslstrip/

- name: conda active sslstrip
  shell: conda activate sslstrip
  args:
    chdir: /home/user/sslstrip/

- name: Run sslstrip
  shell: python setup.py install
  args:
    chdir: /home/user/sslstrip/

...
