---
# This is a role for setting up the client.
- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Install packages
  apt:
    pkg:
     - nmap
     - git
     - python3.8
     - python3-pip
     - apache2
     - net-tools
     - build-essential
     - nano
     - traceroute
     - iputils-ping
    update_cache: yes

- name: Copy buffer1
  copy:
    src: buffer1.c
    dest: /home/client/buffer1.c
    owner: client
    mode: '0755'

- name: Copy buffer2
  copy:
    src: buffer2.cpp
    dest: /home/client/buffer2.cpp
    owner: client
    mode: '0755'


...
