---
# This is a role for setting up the client.
- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Install packages
  apt:
    pkg:
     - nmap
     - git
     - python3.8
     - python3-pip
     - apache2
     - net-tools
     - build-essential
     - nano
     - traceroute
     - iputils-ping
    update_cache: yes

- name: Copy buffer1
  copy:
    src: buffer1.c
    dest: /home/client/buffer1.c
    owner: user
    mode: '0711'

- name: Copy buffer2
  copy:
    src: buffer2.cpp
    dest: /home/client/buffer2.cpp
    owner: user
    mode: '0711'

- name: Complie buffer1
  command: gcc buffer1.c -o buffer1
  args:
    chdir: /home/client/

- name: Complie buffer2
  command: g++ buffer2.cpp -o buffer2
  args:
    chdir: /home/client/

# - name: Change owner of the file
#   file:
#     path: /path/to/your/file.txt
#     owner: your_new_owner
#     state: file

- name: Change permissions (chmod) of the file buffer1
  file:
    path: /home/client/buffer1
    mode: "0711"  # Replace with the desired permission mode
    state: file

- name: Change permissions (chmod) of the file buffer2
  file:
    path: /home/client/buffer2
    mode: "0711"  # Replace with the desired permission mode
    state: file

- name: Delete buffer1 c
  file:
    path: /home/client/buffer1.c
    state: absent

- name: Delete buffer2 cpp
  file:
    path: /home/client/buffer2.cpp
    state: absent
...
