---
# This is a role for setting up the server.

- name: Install packages
  apt:
    pkg:
     - wget
     - net-tools
     - wine
     - libwine
     - curl
    update_cache: yes

- name: Place flag
  copy:
    dest: '/home/server/flag.txt'
    owner: 'server'
    content: "Top_Secret_Flag\n"
    mode: '0777'

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.30.5 client'

- name: change proxy
  script: "export http_proxy='http://192.168.30.5:6996'"

- name: Cron job for auto script curl http
  cron:
   name: "autoscript"
   minute: "*/1" # every 1 minutes
   job: "curl -i -s -k -X $'POST' \
    -H $'Host: testphp.vulnweb.com' -H $'Content-Length: 20' -H $'Cache-Control: max-age=0' -H $'Upgrade-Insecure-Requests: 1' -H $'Origin: http://testphp.vulnweb.com' -H $'Content-Type: application/x-www-form-urlencoded' -H $'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.91 Safari/537.36' -H $'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' -H $'Referer: http://testphp.vulnweb.com/login.php' -H $'Accept-Encoding: gzip, deflate' -H $'Accept-Language: en-US,en;q=0.9' -H $'Connection: close' \
    --data-binary $'uname=test&pass=test' \
    $'http://testphp.vulnweb.com/userinfo.php'"
...
