---
# This is a role for setting up the server.

- name: Install packages
  apt:
    pkg:
     - wget
     - net-tools
     - wine
     - libwine
     - curl
    update_cache: yes

- name: Place flag
  copy:
    dest: '/home/server/flag.txt'
    owner: 'server'
    content: "Top_Secret_Flag\n"
    mode: '0777'

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.30.5 client'

- name: Copy the shell script to the remote server
  copy:
    src: curl_script.sh
    dest: /home/server/curl_script.sh
    mode: '0755'

- name: Add cron job to run the script every 1 minute
  cron:
    name: "Run curl script every 1 minute"
    minute: "*/1"
    job: "/home/server/curl_script.sh"

...
