---
# This is a role for setting up the server.

- name: Install packages
  apt:
    pkg:
     - wget
     - net-tools
     - wine
     - libwine
     - apache2
    update_cache: yes

- name: Place flag
  copy:
    dest: '/home/server/flag.txt'
    owner: 'server'
    content: "Top_Secret_Flag\n"
    mode: '0777'

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.30.5 client'


...
